const artifact = await Bun.file(
  "out/ResearchEscrow.sol/ResearchEscrow.json",
).json();
await Bun.write(
  "shared/abi.ts",
  `// Generated by bun run abi; do not edit.\nexport const escrowAbi = ${JSON.stringify(artifact.abi)} as const;\n`,
);
